apiVersion: tattletale.tattletale.dev/v1beta1
kind: SharedConfigMap
metadata:
  name: sharedconfigmap-sample3
  namespace: tattletale-test
spec:
  sourceConfigMap: tattletale-configmap-sample2
  sourceNamespace: tattletale-test
  targets:
  - namespace: tattletale-test4
  - namespace: tattletale-test5
  - namespace: tattletale-test6
    rename: tattletale-configmap-sample2-renamed
