apiVersion: tattletale.tattletale.dev/v1beta1
kind: SharedSecret
metadata:
  name: sharedsecret-sample1
  namespace: tattletale-test
spec:
  sourceSecret: tattletale-secret-sample1
  sourceNamespace: tattletale-test
  targetNamespaces:
  - tattletale-test1
  - tattletale-test2
  - tattletale-test3
