apiVersion: tattletale.tattletale.dev/v1beta1
kind: SharedConfigMap
metadata:
  name: sharedconfigmap-sample1
  namespace: tattletale-test
spec:
  sourceConfigMap: tattletale-configmap-sample1
  sourceNamespace: tattletale-test
  targets:
  - namespace: tattletale-test1
  - namespace: tattletale-test2
  - namespace: tattletale-test3
    newName: tattletale-configmap-sample1-renamed
