apiVersion: tattletale.tattletale.dev/v1beta1
kind: SharedSecret
metadata:
  name: sharedsecret-sample1
  namespace: tattletale-test
spec:
  sourceSecret: tattletale-secret-sample1
  sourceNamespace: tattletale-test
  targets:
  - namespace: tattletale-test1
  - namespace: tattletale-test2
  - namespace: tattletale-test3
    newName: tattletale-secret-sample1-renamed
