apiVersion: tattletale.tattletale.dev/v1beta1
kind: SharedConfigMap
metadata:
  name: sharedconfigmap-sample3
  namespace: tattletale-test
spec:
  sourceConfigMap: tattletale-configmap-sample2
  sourceNamespace: tattletale-test
  targetNamespaces:
  - tattletale-test4
  - tattletale-test5
  - tattletale-test6
