
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: sharedsecrets.tattletale.tattletale.dev
spec:
  group: tattletale.tattletale.dev
  names:
    kind: SharedSecret
    plural: sharedsecrets
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: SharedSecret is the Schema for the sharedsecrets API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: SharedSecretSpec defines the desired state of SharedSecret
          properties:
            sourceNamespace:
              description: The namespace of the source secret to be shared
              type: string
            sourceSecret:
              description: The name of the source secret to be shared
              type: string
            targetNamespaces:
              description: The list of target namespaces to sync to
              items:
                type: string
              type: array
          required:
          - sourceNamespace
          - sourceSecret
          - targetNamespaces
          type: object
        status:
          description: SharedSecretStatus defines the observed state of SharedSecret
          properties:
            sourceSecret:
              description: The status of the source secret to be shared
              type: string
            targetSecrets:
              description: The status of target secrets to be synched
              items:
                type: string
              type: array
          required:
          - sourceSecret
          - targetSecrets
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
